name: CI-CD

on:
  push:
    branches: [ master, test, dev ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    # check out code to local directory
    - uses: actions/checkout@v2

    # Runs the build script
    - name: Run a bash script
      run: |
        ls -al deploy
        ./deploy/deploy.sh
