name: CI-CD

on:
  push:
    branches: [ master, test, dev ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    # check out code to local directory
    - uses: actions/checkout@v2

    # Runs a single command using the runners shell
    - name: Run a one-line script
      run: |
        printenv
        pwd
        ls -al

    # Runs a set of commands using the runners shell
    - name: Run a multi-line script
      run: |
        echo Add other actions to build,
        echo test, and deploy your project.
