name: CI-CD

on:
  push:
    branches: [ master, test, dev ]

jobs:
  buildAndDeploy:
    runs-on: ubuntu-latest

    steps:
    # check out code to local directory
    - uses: actions/checkout@v2

    # Runs the build script
    - name: Run a bash script
      shell: bash
      env:
        BUCKET_NAME: ${{ secrets.BUCKET_NAME }}
        ACCOUNT_ID: ${{ secrets.ACCOUNT_ID }}
        AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
        AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        AWS_DEFAULT_REGION: ${{ secrets.AWS_DEFAULT_REGION }}
      run: |
        ls -al deploy
        ./deploy/deploy.sh
